steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build --target publish-service -t europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-publish ./src/DfT.DTRO
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build --target search-service -t europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-search ./src/DfT.DTRO
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build --target postgres-migrations-job -t europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-postgres-migrations-job ./src/DfT.DTRO
images:
- 'europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-publish:latest'
- 'europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-search:latest'
- 'europe-west2-docker.pkg.dev/pa-dft-dtro-sandbox/dtro/dtro-prototype-postgres-migrations-job'