# build image for Postgres migrations job
FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:6.0-alpine AS postgres-migrations-job
WORKDIR /app

ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

COPY *.csproj ./
RUN dotnet restore && \
    dotnet tool install --global dotnet-ef --version 6.0.31
ENV PATH="$PATH:/root/.dotnet/tools"

COPY . ./

ENTRYPOINT ["/bin/sh", "-c", "dotnet ef database update"]