# build image for Postgres migrations job
FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:6.0-alpine AS postgres-migrations-job
WORKDIR /app

ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

COPY *.csproj ./
RUN dotnet restore

COPY . ./

ENTRYPOINT ["/bin/sh", "-c", "dotnet tool restore && dotnet ef database update"]