name: Activate User's Application - PROD

on:
  workflow_dispatch:
    inputs:
      app-name:
        type: string
        description: Name of the application to activate
        required: true
      dev-email:
        type: string
        description: Email address of developer the application belongs to
        required: true

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  activate-user-app:
    name: Activate User's Application
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: apigee/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output Workflow Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"

      - name:  Make scripts executable
        run: chmod +x *.sh

      - name: Load Env Vars for Apigee script
        run: |
          echo "workload_identity_service_account=${{ secrets.WIP_SERVICE_ACCOUNT_PROD }}" >> $GITHUB_ENV 
          echo "apigee_organisation=${{ vars.GCP_PROJECT_ID_PROD }}" >> $GITHUB_ENV
          echo "DEV_EMAIL=${{ inputs.dev-email }}" >> $GITHUB_ENV 
          echo "APP_NAME=${{ inputs.app-name }}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_PROD }}
          token_format: access_token

      - name: Set up ApigeeCLI
        run: |
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh
          echo "$HOME/.apigeecli/bin" >> $GITHUB_PATH
          echo "APIGEECLI_DEBUG=true" >> $GITHUB_ENV

      - name: Activate User's Application
        run: ./activate_user_app.sh ${{ steps.google-auth.outputs.access_token }}
