name: Build Feature Branch

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - bug/*
      - hotfix/*
      - DPPB*

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  build-feature:
    name: Build, Test and Verify Feature Branch
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

#      - name: Test
#        run: dotnet test --verbosity normal

      - name: Format check
        run: dotnet format

      - name: Install .NET analyzers
        run: dotnet tool install -g dotnet-format

      - name: Run .NET analyzers
        run: |
          dotnet tool install --global dotnet-format
          dotnet build --no-restore --configuration Release
