name: Delete Dtro Users - INT

on:
  workflow_dispatch:
    inputs:
      user-ids-to-delete:
        type: string
        description: list of user ids to delete(comma separated only)
        required: true

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  delete-dtro-users:
    name: Delete Dtro Users
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: apigee/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  Make scripts executable
        run: chmod +x *.sh

      - name: Load Env Vars for Apigee script
        run: |
          echo "workload_identity_service_account=${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}" >> $GITHUB_ENV 
          echo "apigee_organisation=${{ vars.GCP_PROJECT_ID_TEST }}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{ secrets.CSO_CLIENT_ID_INT }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CSO_CLIENT_SECRET_INT }}" >> $GITHUB_ENV
          echo "DOMAIN=dtro-integration" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
          service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
          token_format: access_token

      - name: Set up ApigeeCLI
        run: |
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh
          echo "$HOME/.apigeecli/bin" >> $GITHUB_PATH
          echo "APIGEECLI_DEBUG=true" >> $GITHUB_ENV

      - name: Delete Dtro Users
        run: ./delete_dtro_users.sh ${{ inputs.user-ids-to-delete }}
