name: Deploy Feature Branch

on:
  workflow_dispatch:
    inputs:
      deploy-to-test:
        type: boolean
        description: Deploy D-TRO application to Test Environment?
        required: false
        default: false
      run-build-push:
        type: boolean
        description: Run Build and Push job?
        required: false
        default: false
      run-deploy-CR-job:
        type: boolean
        description: Run deploy Cloud Run job?
        required: false
        default: false
      run-apigee:
        type: boolean
        description: Run Apigee job?
        required: false
        default: false

jobs:
  deploy-feature-dev:
    if: ${{ ! inputs.deploy-to-test }}
    name: Deploy Feature Branch to Dev
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
      service_ui_client_id: ${{ secrets.CSO_CLIENT_ID_DEV }}
      service_ui_client_secret: ${{ secrets.CSO_CLIENT_SECRET_DEV }}
      gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-project: ${{ vars.GCP_PROJECT_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
      service-ui-image-name: ${{ vars.DTRO_SERVICE_UI_IMAGE_NAME }}
      service-ui-image-tag: ${{ vars.DTRO_SERVICE_UI_IMAGE_TAG }}
      # do-validation-checks: true
      run-build-push: ${{ inputs.run-build-push }}
      run-deploy-CR-job: ${{ inputs.run-deploy-CR-job }}
      run-apigee: ${{ inputs.run-apigee }}

  deploy-feature-test:
   if: ${{ inputs.deploy-to-test }}
   name: Deploy to Test
   uses: ./.github/workflows/deploy_resources.yml
   secrets:
     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
     wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
     execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT_TEST }}
     service_ui_client_id: ${{ secrets.CSO_CLIENT_ID_TEST }}
     service_ui_client_secret: ${{ secrets.CSO_CLIENT_SECRET_TEST }}
     gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_TEST }}
   with:
     gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
     gcp-project: ${{ vars.GCP_PROJECT_ID_TEST }}
     gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
     environment: test
     dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
     dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
     service-ui-image-name: ${{ vars.DTRO_SERVICE_UI_IMAGE_NAME }}
     service-ui-image-tag: ${{ vars.DTRO_SERVICE_UI_IMAGE_TAG }}
     # do-validation-checks: true
     run-build-push: ${{ inputs.run-build-push }}
     run-deploy-CR-job: ${{ inputs.run-deploy-CR-job }}
     run-apigee: ${{ inputs.run-apigee }}
