name: Deploy Feature Branch

on:
  workflow_dispatch:
    inputs:
      deploy-to-test:
        type: boolean
        description: Deploy D-TRO application to Test Environment?
        required: false
        default: false
      run-build-push:
        type: boolean
        description: Run Build and Push job?
        required: false
        default: false
      run-deploy-CR-job:
        type: boolean
        description: Run deploy Cloud Run job?
        required: false
        default: false
      run-apigee:
        type: boolean
        description: Run Apigee job?
        required: false
        default: false

jobs:
  deploy-feature-dev:
    if: ${{ ! inputs.deploy-to-test }}
    name: Deploy Feature Branch to Dev
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
      gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-project: ${{ vars.GCP_PROJECT_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
      # do-validation-checks: true
      run-build-push: ${{ inputs.run-build-push }}
      run-deploy-CR-job: ${{ inputs.run-deploy-CR-job }}
      run-apigee: ${{ inputs.run-apigee }}

  run-api-tests-on-dev:
    name: Run API tests on dev after deployment to dev is complete
    needs: deploy-feature-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: API tests
      id: api-tests
      run: |
        ./run_api_tests.sh -e dev -ai ${{ secrets.CSO_CLIENT_ID_DEV }} -as ${{ secrets.CSO_CLIENT_SECRET_DEV }} -ci ${{ secrets.CONSUMER_CLIENT_ID_DEV }} -cs ${{ secrets.CONSUMER_CLIENT_SECRET_DEV }} -pi1 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_ID_1_DEV }} -ps1 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_SECRET_1_DEV }} -ti1 99999 -pi2 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_ID_2_DEV }} -ps2 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_SECRET_2_DEV }} -ti2 99998

    - name: Upload API test results
      if: always() && steps.api-tests.outcome != 'skipped'
      uses: actions/upload-artifact@v4
      with:
        name: API test results
        path: Src/DfT.DTRO.ApiTests/TestResults/test-results.html

  deploy-feature-test:
   if: ${{ inputs.deploy-to-test }}
   name: Deploy to Test
   uses: ./.github/workflows/deploy_resources.yml
   secrets:
     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
     wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
     execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT_TEST }}
     gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_TEST }}
   with:
     gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
     gcp-project: ${{ vars.GCP_PROJECT_ID_TEST }}
     gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
     environment: test
     dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
     dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
     # do-validation-checks: true
     run-build-push: ${{ inputs.run-build-push }}
     run-deploy-CR-job: ${{ inputs.run-deploy-CR-job }}
     run-apigee: ${{ inputs.run-apigee }}

  run-api-tests-on-test:
    name: Run API tests on test after deployment to test is complete
    needs: deploy-feature-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: API tests
      id: api-tests
      run: |
        ./run_api_tests.sh -e test -ai ${{ secrets.CSO_CLIENT_ID_TEST }} -as ${{ secrets.CSO_CLIENT_SECRET_TEST }} -ci ${{ secrets.CONSUMER_CLIENT_ID_TEST }} -cs ${{ secrets.CONSUMER_CLIENT_SECRET_TEST }} -pi1 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_ID_1_TEST }} -ps1 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_SECRET_1_TEST }} -ti1 99999 -pi2 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_ID_2_TEST }} -ps2 ${{ secrets.API_TESTS_PUBLISHER_CLIENT_SECRET_2_TEST }} -ti1 99998

    - name: Upload API test results
      if: always() && steps.api-tests.outcome != 'skipped'
      uses: actions/upload-artifact@v4
      with:
        name: API test results
        path: Src/DfT.DTRO.ApiTests/TestResults/test-results.html
