name: Build and push Docker image to Artifact Registry

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    name: Authenticate with Google and push the container to the Artifact Registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.3.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}

      - name: Authenticate Docker with the Artifact Registry repository
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push DTRO Docker image to Artifact Registry
        uses: docker/build-push-action@v6.1.0
        with:
          context: dft-dtro-beta/Src/DfT.DTRO
          platforms: linux/amd64
          push: true
          provenance: false
          tags: europe-west1-docker.pkg.dev/dft-dtro-dev-01/dft-dtro-dev-repository/dft-dtro-beta_test:latest
