name: Merge To Main

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
      service_ui_client_id: ${{ secrets.CSO_CLIENT_ID_DEV }}
      service_ui_client_secret: ${{ secrets.CSO_CLIENT_SECRET_DEV }}
      gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_DEV }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-project: ${{ vars.GCP_PROJECT_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
      service-ui-image-name: ${{ vars.DTRO_SERVICE_UI_IMAGE_NAME }}
      service-ui-image-tag: ${{ vars.DTRO_SERVICE_UI_IMAGE_TAG }}
      run-build-push: true
      run-deploy-CR-job: true
#      run-apigee: false #TODO: Default value when no major endpoint or OAuth changes have been made
      run-apigee: true

  deploy-test:
    name: Deploy to Test
    uses: ./.github/workflows/deploy_resources.yml
    needs:
      - deploy-dev
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_TEST }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT_TEST }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT_TEST }}
      service_ui_client_id: ${{ secrets.CSO_CLIENT_ID_TEST }}
      service_ui_client_secret: ${{ secrets.CSO_CLIENT_SECRET_TEST }}
      gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER_TEST }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
      gcp-project: ${{ vars.GCP_PROJECT_ID_TEST }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: test
      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
      service-ui-image-name: ${{ vars.DTRO_SERVICE_UI_IMAGE_NAME }}
      service-ui-image-tag: ${{ vars.DTRO_SERVICE_UI_IMAGE_TAG }}
      run-build-push: true
      run-deploy-CR-job: true
#      run-apigee: false #TODO: Default value when no major endpoint or OAuth changes have been made
      run-apigee: true
