name: Merge To Main

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/deploy_resources.yml
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
    with:
      gcp-project-id: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-project: ${{ vars.GCP_PROJECT_ID_DEV }}
      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
      environment: dev
      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
      # TODO: In here to support apigee deployment. To be removed once Apigee deployment completed.
      run-build-push: true
      run-deploy-CR-job: true
      run-apigee: false

#  deploy-test:
#    name: Deploy to Test
#    uses: ./.github/workflows/deploy_resources.yml
#    needs:
#      - deploy-dev
#    secrets:
#      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#      wip_service_account: ${{ secrets.WIP_SERVICE_ACCOUNT }}
#      execution_service_account: ${{ secrets.EXECUTION_SERVICE_ACCOUNT }}
#    with:
#      gcp-project-id: ${{ vars.GCP_PROJECT_ID_TEST }}
#      gcp-project: ${{ vars.GCP_PROJECT_ID_TEST }}
#      gcp-region: ${{ vars.DEFAULT_GCP_REGION }}
#      environment: dev
#      dtro-image-name: ${{ vars.DTRO_IMAGE_NAME }}
#      dtro-image-tag: ${{ vars.DTRO_IMAGE_TAG }}
